In [1]:
import numpy as np

In [8]:
sc_coverage = np.array([[[1,2],[3,4],[100,101]], [[-1,-2],[-3,-4],[-100,-101]]])
print(sc_coverage)
sc_coverage.shape

[[[   1    2]
  [   3    4]
  [ 100  101]]

 [[  -1   -2]
  [  -3   -4]
  [-100 -101]]]


(2, 3, 2)

In [14]:
min_reads = 10
min_cells = 1

In [15]:
sc_coverage.sum(axis=2)

array([[   3,    7,  201],
       [  -3,   -7, -201]])

In [35]:
counts_filter = np.where((sc_coverage.sum(axis=2) >= min_reads).sum(axis=0) >= min_cells)[0]
counts_filter
#(np.where(counts_filter)[0])

array([2])

In [38]:
sc_coverage[:, counts_filter
]

array([[[ 100,  101]],

       [[-100, -101]]])

In [40]:
np.zeros(shape=[len([1]), 16571, len([0,1])])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
x


array([[[   1,    2],
        [   3,    4],
        [ 100,  101]],

       [[  -1,   -2],
        [  -3,   -4],
        [-100, -101]]])

In [41]:
from sklearn.mixture import GaussianMixture


In [43]:
bq_vals = x.flatten()

In [57]:
gm = GaussianMixture(n_components=3)

In [58]:
gm.fit(bq_vals.reshape([len(bq_vals),1]))

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
                means_init=None, n_components=3, n_init=1, precisions_init=None,
                random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
                verbose_interval=10, warm_start=False, weights_init=None)

In [59]:
gm.weights_

array([0.16666667, 0.66666667, 0.16666667])

In [60]:
gm.means_

array([[ 1.00500000e+002],
       [-4.44571129e-289],
       [-1.00500000e+002]])

In [61]:
gm.covariances_

array([[[0.250001]],

       [[7.500001]],

       [[0.250001]]])

In [62]:
gm.converged_

True

In [67]:
len(bq_vals)


12

In [72]:
bq_vals = x.flatten()
bq_vals = bq_vals.reshape([len(bq_vals),1])

#print(gm.predict_proba(bq_vals.reshape([len(bq_vals),1])).shape)


top_bq_mean = np.argmax(gm.means_)
gm.predict_proba(bq_vals)[:, top_bq_mean]

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.])

In [74]:
top_bq_mean

0

In [73]:
bq_vals = x.flatten()
bq_vals = bq_vals.reshape([len(bq_vals),1])

#print(gm.predict_proba(bq_vals.reshape([len(bq_vals),1])).shape)


top_bq_mean = np.argmax(gm.means_)
gm.predict_proba(bq_vals)

array([[0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 3.55656359e-290, 0.00000000e+000],
       [1.00000000e+000, 5.38871601e-296, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 3.55656359e-290, 1.00000000e+000],
       [0.00000000e+000, 5.38871601e-296, 1.00000000e+000]])

In [ ]:
for ind, val in enumerate(bq_vals):
    